[project]
name = "data-setup"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mayank Joshi", email = "mayankjoshi@medlaunchconcepts.com" }
]
requires-python = ">=3.13"
dependencies = [
    "psycopg2-binary>=2.9.12",
]

[project.scripts]
data-setup = "data_setup:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
